### ISSUE TITLE
subscriptions

### ISSUE THREAD

**Issue by suenot** [tarantool/graphql.0#290] opened 2019-12-11 18:55 UTC
Subscriptions are most important feature for real time apps.
Maybe need to use https://github.com/tarantool/websocket project.

I don't know how subscriptions realized in other graphql frameworks,
but I can offer my strategy:
1. Data pushed to tarantool (maybe with queue)
2. Checking subscriptions/users that wait this data
3. Is subscriptions/users exist, need to push data to websocket channel with unique name
- also need to run tarantool cron, that will be clear unused subscriptions/users

Origin of the issue and start of the discussion: PR #216.

**Comment by Totktonada** [comment] 2019-12-11 21:11
This project is a kind of mapping between tarantool database, avro schemas and graphql data model. It is not about ability to expose custom API from tarantool using graphql. This was the experiment and now we don't have resources to continue. Aside of that, there are implementation details that I would make in other way then it is now (I consider them as broken by design). I should add a note to README.

Anyway, I plan to rename this repository (to save issues and so) and fork https://github.com/bjornbytes/graphql-lua to tarantool/graphql and push some enhancements I made here: say, better arguments validation. So, tarantool/graphql will be basically just enhanced graphql-lua: this way is more flexible, that is vital for many projects.

Maybe we'll return back to some kind of mapping between tarantool spaces to graphql objects, but now we don't have such plans.

**Comment by Totktonada** [comment] 2022-04-13 22:57
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide

**Closed as completed by Totktonada** 2022-04-13 22:57 UTC
Labels: wontfix, feature, archived
