### ISSUE TITLE
Add support of fragments' arguments

### ISSUE THREAD

**Issue by SudoBobo** [tarantool/graphql.0#89] opened 2018-03-16 12:39 UTC
Currently they are not supported by graphql-lua. This will NOT work:
```
... on Image (size: small) {
    resolution
    uploadedAt
}
```
It reduces feature capacity of union connections in compare with 'single' ones, as fragments are the only way to access union fields. See https://github.com/facebook/graphql/issues/204

**Comment by Totktonada** [comment] 2018-09-16 19:54
I think we can add arguments to 'box field' in order to support arguments for multi-head connections.

**Comment by Totktonada** [comment] 2018-09-16 20:00
I'll close it as dupe of more general #185.

**Closed as completed by Totktonada** 2018-09-16 20:00 UTC
Labels: enhancement, prio2
