### ISSUE TITLE
Connection index loss during accessor constructing

### ISSUE THREAD

**Issue by SudoBobo** [tarantool/graphql.0#88] opened 2018-03-16 11:50 UTC
Our current formats of connections (both simple and union) have 'index_name' field representing the index that should be used in  fetching data from destination collection. In some cases this index is lost during accessor constructing (in `accessor_general/build_connection_indexes`):

```
    for collection_name, collection in pairs(collections) do
        for _, c in ipairs(collection.connections) do
            connection_indexes[c.destination_collection][c.name] = set_connection_index(...)
```
Here is the case: consider A → C and B → C connections with the same names. Only last one will be saved in the connection_indexes structure and A → C connection can fail during execution.
Another case is when different variants (in union connection) points to the same destination collection.
```
    for collection_name, collection in pairs(collections) do
        for _, c in ipairs(collection.connections) do
            for _, v in ipairs(c.variants) do
                connection_indexes[v.destination_collection][c.name] = set_connection_index(...)
```

**Comment by Totktonada** [comment] 2018-03-17 02:53
Dupe of #70?

**Comment by Totktonada** [comment] 2022-04-13 22:36
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide

**Closed as completed by Totktonada** 2022-04-13 22:36 UTC
Labels: bug, wontfix, archived
